# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64

channels:
  - astropy

dependencies:
  - python>=3
  - astropy>=1.1.2
  - jupyter>=1.0.0
  - matplotlib>=1.5.1
  - numpy>=1.11.0
  - scikit-learn>=0.18.1
  - scipy>=0.17.0
  - iminuit>=0.12

  - pip:
    - sncosmo>=1.3.0
    - tflearn
